### ISSUE TITLE
createSubscription function does not exists

### ISSUE THREAD

**Issue by hiraaziz** [getsafepay/safepay-node#20]
## I'm submitting a bug report
![image](https://github.com/getsafepay/safepay-node/assets/66185332/acb67f39-fe8f-43ab-8e24-3c84392c1155)

## What is the current behavior?
When I try to create a subscription using the Safepay NodeJS SDK, I receive a TypeError indicating that safepay.checkout.createSubscription is not a function.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Set up a Next.js 13 API route.
Install and import @sfpy/node-sdk.
Initialize Safepay with the given credentials.
Call the safepay.checkout.createSubscription method.
Observe the error in the console.

## What is the expected behavior?
The safepay.checkout.createSubscription method should execute successfully, and I should be able to generate a subscription URL without encountering any errors.

## What is the motivation / use case for changing the behavior?
To successfully integrate Safepay subscription payments into my application.

## Please tell us about your environment:
Browser: Chrome (latest version)

Environment:  Sandbox

- [ ] Production
- [ yes] Sandbox
- [ ] Development

**Comment by ziyadparekh** [comment]
hi @hiraaziz thanks for reporting this bug.

This is due to the subscriptions functionality in the SDK not being published to NPM. I have just published a new version of the node SDK to npm so if you reinstall it you should be able to play around with subscriptions.

Please note that we have pushed a major version upgrade so make sure you are installing `@sfpy/node-sdk@3.0.0` 

Let me know if this works

**Comment by hiraaziz** [comment]
Is this subscription feature is available only to those who have signed for production or I can use in test mode?

**Comment by hiraaziz** [comment]
Sure,
1. Here is the sdk version Iam using: 
![image](https://github.com/getsafepay/safepay-node/assets/66185332/cb0fed5d-e1b9-49e6-8269-51914a958283)

2. Here is the configuration :
![image](https://github.com/getsafepay/safepay-node/assets/66185332/dc2319bf-8b65-436e-a485-dd5a58e06725)

3. Public API KEY: sec_a1732c22-bc53-4ba5-8928-533d6e506e37

4. This is the error Iam getting: 
![image](https://github.com/getsafepay/safepay-node/assets/66185332/0161b94d-7a7b-4f55-adfb-296f0c0194f5)

**Comment by ziyadparekh** [comment]
Thanks @hiraaziz 

I have published a new minor version `3.0.1`. Can you try again? On our side all the tests are working fine including tests for subscriptions.

Apologies for the trouble you're facing but would you mind re-installing and trying again? making sure the version is `3.0.1`

**Comment by ziyadparekh** [comment]
@fatimaaurangzeb0640 Please see what the issue could be so we can help @hiraaziz out

**Comment by hiraaziz** [comment]
Now its working fine. @ziyadparekh

**Comment by ziyadparekh** [comment]
Hey @hiraaziz subscriptions have to confirmed by the customer not the merchant. When you use the SDK to create a subscription, the URL you receive in the response is what your system has to redirect the customer to. 

To test it out you should console log the URL and paste it in your browser. 

Once your browser opens the checkout page, you will be prompted to 
1. create a Safepay account
2. save a card 
3. subscribe to the plan 

let me know if this helps

**Comment by hiraaziz** [comment]
@ziyadparekh 1. I need to know if customer successfully subscribed then after redirecting him to success page I want to add his id into db but I need to confirm his subscription with some API not via merchant dashboard. 

2. Can you please tell how can I get the subscription id of customer on the client side after subscribing - any API for this. We have only auth token and planid!

3. Is there any other guide for developers other than this readme file?

**Comment by ziyadparekh** [comment]
Hi @hiraaziz whenever a new subscription is entered into by your customer, a webhook is fired to your backend indicating the details of the subscription. In order for Safepay to send the webhook, you first have to subscribe to the webhook through your dashboard.

1. Navigate to the developers section of your dashboard and then go the Endpoints subsection. 
2. From there, you may first have to enable webhooks, but after that click on Add an Endpoint. 
3. Next, enter the URL of an endpoint that lives on your server where you wish to receive the webhooks. Make sure this is not a localhost URL. If you are developing on localhost, please use Ngrok and use that URL
4. After creating the Endpoint, click on the Action Button on the row (button with 3 dots) and click on "Details".
5. Inside the modal that opens (wait for the modal to load) you can select the events you are interested in receiving. For subscriptions you should subscribe to the following events:
     - `subscription:created`
     - `subscription:unpaid`
     - `subscription:ended`
     - `subscription_payment:complete`
     - `subscription_payment:failed`
6. Its your decision whether you want to handle all of these events through one URL or create multiple endpoints for each type of event.

We are working on more comprehensive documentation for Webhooks, but for now the JSON for a `subscription:created` event looks like this

```json
{
  "created_at": "2023-07-28T10:22:15Z",
  "notification_id": "CJ1P8O7SO29C73B13PJ0",
  "payload": {
    "kind": "Subscription_Created",
    "subject": {
      "subscription": {
        "balance": "0",
        "billing_cycle_anchor": "2023-07-28T10:11:44.310231756Z",
        "created_at": "2023-07-28T10:11:44.310231756Z",
        "current_period_end_date": "2023-07-29T10:11:43.310231756Z",
        "current_period_start_date": "2023-07-28T10:11:44.310231756Z",
        "instrument_id": "tms_e2254483-1947-4c1b-9852-d768495e60e6",
        "never_expires": true,
        "plan": {
          "active": true,
          "amount": "4000",
          "created_at": "2023-06-20T11:12:45Z",
          "currency": "PKR",
          "interval": "DAY",
          "interval_count": 1,
          "merchant_api_key": "sec_edeade52-46aa-483b-b87d-009d3ce41554",
          "name": "Messaging",
          "product": "product_identifier",
          "token": "plan_b25d9e71-73a7-43f2-910a-fa8152405fbc",
          "type": "RECURRING",
          "updated_at": "2023-06-20T11:12:45Z"
        },
        "plan_id": "plan_b25d9e71-73a7-43f2-910a-fa8152405fbc",
        "price_amount": "4000",
        "price_currency": "PKR",
        "start_date": "2023-07-28T10:11:44.310231756Z",
        "status": "INCOMPLETE",
        "token": "sub_49ae5d29-7d0b-409b-b8a7-9db9e59c15b0",
        "updated_at": "2023-07-28T10:11:44.310231756Z",
        "user_id": "user_bb9cf861-cdc5-41c4-abff-509f4dd86609"
      }
    },
    "timestamp": "2023-07-28T10:11:44.389102006Z"
  },
  "token": "CJ1P8O7SO29C73B13PJG",
  "updated_at": "2023-07-28T10:22:15Z"
}
```

**Comment by hiraaziz** [comment]
@ziyadparekh subscription activation takes weeks in sandbox account.. Is this same for production account?

**Comment by fatimaaurangzeb0640** [comment]
hey @hiraaziz what does the subscription status say before it becomes active?

**Comment by hiraaziz** [comment]
@fatimaaurangzeb0640 it says trailing. In sandbox account, After few weeks I got email that says my subscription is now activated. Then the status was changed to active.
How much time subscription activation takes in production account.

**Comment by fatimaaurangzeb0640** [comment]
In both sandbox and production, the subscription becomes active after the trial period is over. When the subscription's trial period is going, its status is 'TRAILING' and when the trial period is over, the subscription finally becomes active, and the status is changed to 'ACTIVE'. This is also when you get charged for the first time. 

If you want the subscription to be active right away, you should set the trial period to 0 (days) when creating the plan or you can even update the plan and set the trial period to 0. What is the trial period for the plan that you subscribed to?

**Comment by hiraaziz** [comment]
@fatimaaurangzeb0640 got it. 
Kindly check this here is an endpoint for webhook
<img width="691" alt="image" src="https://github.com/getsafepay/safepay-node/assets/66185332/ff50b756-f4a5-4606-b9f9-35343b198c12">
Is this line "const valid = safepay.verify.webhook(request)" correct? because I am getting error in this line.

here is subscription api 
<img width="691" alt="image" src="https://github.com/getsafepay/safepay-node/assets/66185332/b4d05d8e-2eab-43ae-9368-19872cc33678">

**Comment by fatimaaurangzeb0640** [comment]
@hiraaziz hey can you please share two things with me:

1.  the `request` json object that you are trying to verify
2. the `error` that you receive in your `catch` while verifying the `request`

**Comment by hiraaziz** [comment]
This is url : https://295plan.vercel.app/payment
I have set trial period to 0 , now when I subscribe it says incomplete status
<img width="516" alt="image" src="https://github.com/getsafepay/safepay-node/assets/66185332/4e03cf75-f539-4b96-884e-209ed04fe4e3">

this is error : 
<img width="607" alt="image" src="https://github.com/getsafepay/safepay-node/assets/66185332/84455cd3-973d-4d8f-a817-5c46b65ff495">

This is request json : 
NextRequest [Request] {
  [Symbol(realm)]: {
    settingsObject: { baseUrl: undefined, origin: [Getter], policyContainer: [Object] }
  },
  [Symbol(state)]: {
    method: 'POST',
    localURLsOnly: false,
    unsafeRequest: false,
    body: { stream: undefined, source: null, length: null },
    client: { baseUrl: undefined, origin: [Getter], policyContainer: [Object] },
    reservedClient: null,
    replacesClientId: '',
    window: 'client',
    keepalive: false,
    serviceWorkers: 'all',
    initiator: '',
    destination: '',
    priority: null,
    origin: 'client',
    policyContainer: 'client',
    referrer: 'client',
    referrerPolicy: '',
    mode: 'cors',
    useCORSPreflightFlag: true,
    credentials: 'same-origin',
    useCredentials: false,
    cache: 'default',
    redirect: 'follow',
    integrity: '',
    cryptoGraphicsNonceMetadata: '',
    parserMetadata: '',
    reloadNavigation: false,
    historyNavigation: false,
    userActivation: false,
    taintedOrigin: false,
    redirectCount: 0,
    responseTainting: 'basic',
    preventNoCacheCacheControlHeaderModification: false,
    done: false,
    timingAllowFailed: false,
    headersList: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: [Array]
    },
    urlList: [ [URL] ],
    url: URL {
      href: 'https://295plan.vercel.app/api/webhooks',
      origin: 'https://295plan.vercel.app',
      protocol: 'https:',
      username: '',
      password: '',
      host: '295plan.vercel.app',
      hostname: '295plan.vercel.app',
      port: '',
      pathname: '/api/webhooks',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    }
  },
  [Symbol(signal)]: AbortSignal { aborted: false },
  [Symbol(abortController)]: AbortController { signal: AbortSignal { aborted: false } },
  [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(28) {
      'accept' => [Object],
      'accept-encoding' => [Object],
      'connection' => [Object],
      'content-length' => [Object],
      'content-type' => [Object],
      'forwarded' => [Object],
      'host' => [Object],
      'user-agent' => [Object],
      'x-forwarded-for' => [Object],
      'x-forwarded-host' => [Object],
      'x-forwarded-proto' => [Object],
      'x-matched-path' => [Object],
      'x-real-ip' => [Object],
      'x-sfpy-signature' => [Object],
      'x-vercel-deployment-url' => [Object],
      'x-vercel-forwarded-for' => [Object],
      'x-vercel-id' => [Object],
      'x-vercel-ip-country' => [Object],
      'x-vercel-ip-country-region' => [Object],
      'x-vercel-ip-latitude' => [Object],
      'x-vercel-ip-longitude' => [Object],
      'x-vercel-ip-timezone' => [Object],
      'x-vercel-proxied-for' => [Object],
      'x-vercel-proxy-signature' => [Object],
      'x-vercel-proxy-signature-ts' => [Object],
      'x-vercel-sc-basepath' => [Object],
      'x-vercel-sc-headers' => [Object],
      'x-vercel-sc-host' => [Object]
    },
    [Symbol(headers map sorted)]: [
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array], [Array], [Array],
      [Array]
    ]
  },
  [Symbol(internal request)]: {
    cookies: RequestCookies { _parsed: Map(0) {}, _headers: [HeadersList] },
    geo: {},
    ip: undefined,
    nextUrl: NextURL { [Symbol(NextURLInternal)]: [Object] },
    url: 'https://295plan.vercel.app/api/webhooks'
  }
}

Error:
Error processing webhook: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at Verify.webhook (/var/task/.next/server/chunks/2152.js:769:27)
    at POST (/var/task/.next/server/app/api/webhooks/route.js:129:38)
    at /var/task/.next/server/chunks/5501.js:5294:43
    at /var/task/.next/server/chunks/5501.js:6161:36
    at NoopContextManager.with (/var/task/.next/server/chunks/5501.js:583:30)
    at ContextAPI.with (/var/task/.next/server/chunks/5501.js:253:58)
    at NoopTracer.startActiveSpan (/var/task/.next/server/chunks/5501.js:1176:34)
    at ProxyTracer.startActiveSpan (/var/task/.next/server/chunks/5501.js:1216:36) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by fatimaaurangzeb0640** [comment]
hey @hiraaziz please bear with me while I am trying to see on my side why you are getting this error. will get back to you as soon as I can

**Comment by fatimaaurangzeb0640** [comment]
hey @hiraaziz i looked into the issue and i think you need to parse your `request` object like this since you are using Next:

``` const body = await request.json(); ```

can you please do this and share with me what you get? or is this how you are already doing it?
here's the source for this solution: https://github.com/vercel/next.js/discussions/46483
